---
creation_rules:
  - age: >-
      age1ffpuwpu04nqk3lz42qw8snlqaapn63k58q8ptxf9r2tkmmtxrg9qzqvf0v
    path_regex: ^talos/talsecret.sops.yaml$
  - age: >-
      age1ffpuwpu04nqk3lz42qw8snlqaapn63k58q8ptxf9r2tkmmtxrg9qzqvf0v
    path_regex: ^k8s/
    encrypted_regex: '^(data|stringData)$'
