apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nats-io.github.io/k8s/helm/charts/
      chart: nats
      version: '1.3.2'
      sourceRef:
        kind: HelmRepository
        name: nats-charts
        namespace: flux-system
  values:
    config:
      jetstream:
        enabled: true
