apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://traefik.github.io/charts
      chart: traefik
      version: '35.0.0'
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  values:
    ports:
      web:
        asDefault: true
        forwardedHeaders:
          trustedIPs:
          - 192.168.30.0/24
      websecure: null
    ingressRoute:
      dashboard:
        enabled: true
      healthcheck:
        enabled: true
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: '192.168.40.240'
