apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://cloudnative-pg.github.io/charts
      chart: cloudnative-pg
      version: '0.23.2'
      sourceRef:
        kind: HelmRepository
        name: cnpg-charts
        namespace: flux-system
