---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-app
  namespace: flux-system
spec:
  path: ./k8s/apps/metallb
  targetNamespace: metallb-system
  interval: 10m
  prune: true
  dependsOn:
    - name: charts
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  path: ./k8s/apps/metallb/config
  targetNamespace: metallb-system
  interval: 10m
  prune: true
  dependsOn:
    - name: metallb-app
  sourceRef:
    kind: GitRepository
    name: flux-system

