---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nats
  namespace: flux-system
spec:
  path: ./k8s/apps/nats
  targetNamespace: nats-system
  interval: 10m
  prune: true
  dependsOn:
    - name: charts
  sourceRef:
    kind: GitRepository
    name: flux-system
