---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: charts
  namespace: flux-system
spec:
  path: ./k8s/apps
  targetNamespace: flux-system
  interval: 10m
  prune: true
  dependsOn:
    - name: charts
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
