---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  path: ./k8s/seabird/seabird-core
  targetNamespace: seabird-core
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
