---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg-charts
  namespace: flux-system
spec:
  interval: 60m
  url: https://cloudnative-pg.github.io/charts
  timeout: 3m

